# Generated by Django 4.2.11 on 2024-07-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text='Tell us your age (in years) so we can personalize your experience!', max_length=2)),
                ('fitness_goals', models.CharField(help_text='Your Fitness Goals: What are you aiming for?', max_length=100)),
                ('food_goals', models.CharField(help_text='Nutritional Objectives: Tell us about your dietary goals!', max_length=100)),
                ('lifestyle', models.CharField(blank=True, help_text='Could you share what your typical day looks like?', max_length=200, null=True)),
            ],
            options={
                'ordering': ['age', 'fitness_goals', 'food_goals', 'lifestyle'],
            },
        ),
    ]
