# Generated by Django 5.0.6 on 2024-07-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(choices=[('A', '18 - 30'), ('B', '31 - 43'), ('C', '44 - 56'), ('D', '57 - 69'), ('E', '70 +')], default='A', help_text='Tell us your age (in years) so we can personalize your experience!')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1)),
                ('fitness_goals', models.TextField(help_text='Your Fitness Goals: What are you aiming for?', max_length=100)),
                ('lifestyle', models.TextField(blank=True, help_text='Could you share what your typical fitness routine involves?', max_length=200, null=True)),
            ],
            options={
                'ordering': ['gender', 'age_range', 'fitness_goals', 'lifestyle'],
            },
        ),
    ]
