# Generated by Django 4.2.11 on 2024-07-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LatelyFit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(help_text='Tell us your age (in years) so we can personalize your experience!'),
        ),
    ]
