# Generated by Django 4.2.11 on 2024-07-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LatelyFit', '0002_alter_person_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['gender', 'age', 'fitness_goals', 'food_goals', 'lifestyle']},
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(choices=[('A', '18 - 30'), ('B', '31 - 43'), ('C', '44 - 56'), ('D', '57 - 69'), ('E', '70 and up')], default='A', help_text='Tell us your age (in years) so we can personalize your experience!'),
        ),
    ]
