# Generated by Django 4.2.11 on 2024-07-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LatelyFit', '0003_alter_person_options_person_gender_alter_person_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['gender', 'age_range', 'fitness_goals', 'food_goals', 'lifestyle']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.AddField(
            model_name='person',
            name='age_range',
            field=models.CharField(choices=[('A', '18 - 30'), ('B', '31 - 43'), ('C', '44 - 56'), ('D', '57 - 69'), ('E', '70 +')], default='A', help_text='Tell us your age (in years) so we can personalize your experience!'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fitness_goals',
            field=models.TextField(help_text='Your Fitness Goals: What are you aiming for?', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='food_goals',
            field=models.TextField(help_text='Nutritional Objectives: Tell us about your dietary goals!', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='lifestyle',
            field=models.TextField(blank=True, help_text='Could you share what your typical fitness routine involves?', max_length=200, null=True),
        ),
    ]
